name: simple action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: the simple action
        run: echo "this is a very simple Github Actions task"